### ISSUE TITLE
Corbeille (2)

### ISSUE THREAD

**Issue by Nicolas-L** [docalist/docalist#338]
Suite au ticket fermé #289, j'ai refait quelques tests sur le .NET, cela semble marcher.

Par contre, en voulant mettre des notices à la corbeille puis, en voulant les rétablir (action groupée sur plus de 10 notices), un **message d'erreur** apparaît : 

>Fatal error: Uncaught exception 'Docalist\Repository\Exception\RepositoryException' with message 'JSON error while decoding entity 3367254: error 4' in /var/www/documentation-sociale.net/web/plugins/docalist-core/class/Repository/Repository.php:259 Stack trace: #0 /var/www/documentation-sociale.net/web/plugins/docalist-core/class/Repository/PostTypeRepository.php(426): Docalist\Repository\Repository->decode('{"ref":78776,"t...', 3367254) #1 /var/www/documentation-sociale.net/web/plugins/docalist-biblio/class/Database.php(568): Docalist\Repository\PostTypeRepository->decode(Array, 3367254) #2 /var/www/documentation-sociale.net/web/plugins/docalist-biblio/class/Database.php(206): Docalist\Biblio\Database->decode(Array, 3367254) #3 /var/www/documentation-sociale.net/web/plugins/docalist-biblio/class/DatabaseIndexer.php(63): Docalist\Biblio\Database->fromPost(Object(WP_Post), 'content') #4 /var/www/documentation-sociale.net/web/plugins/docalist-search/class/TypeIndexer.php(127): Docalist\Biblio\DatabaseIndexer->map(Object(WP_ in /var/www/documentation-sociale.net/web/plugins/docalist-core/class/Repository/Repository.php on line 259

Malgré les apparences, l'action est réalisée car quand on quitte l'écran puis qu'on réactualise, tout est OK.

Je n'ai pas essayé sur le .ORG

**Comment by Nicolas-L** [comment]
Plus embêtant,

en faisant cette manip, j'ai l'impression que les notices 78766 et 78753 ont scratché... (sur le .NET). Elles sont revenues sur la liste de notices validées mais on n'a plus accès a leur contenu

![capture](https://cloud.githubusercontent.com/assets/5398758/9439967/f7115eba-4a6b-11e5-9a88-0b57bf8f6e88.JPG)

Si on clique dessus : Fatal error

**Comment by daniel-menard** [comment]
Ce ticket est vraiment embêtant car on perd complètement les données des notices : lors des tests faits par Nicolas on a ainsi perdu les notices de test faites par Olivier sur le .net pour le répertoire des revues (j'ai depuis restauré une sauvegarde de la base pour récupérer les notices perdues).

J'ai passé quasiment toute la journée à investiguer ce bug et en fait c'est un bug WordPress...

Le problème est lié à la présence ou non d'un antislash (`\`) dans l'un des champs de la notice : lorsque la notice est mise à la corbeille, WordPress supprime sans autre manière tous les antislash qu'il trouve.

On peut facilement tester le problème avec les articles et les pages WordPress : si on saisit un post qui contient des `\` (dans le titre ou dans le contenu) et qu'on le met à la corbeille, les antislashs ont disparu lorsqu'on restaure le post.

En usage "normal" de WordPress, ce n'est pas trop gênant car on n'a pas souvent des antislashs dans les articles.

Mais dans notre cas on stocke du JSON dans nos notices, et en JSON les caractères spéciaux (guillemet double par exemple) doivent être "échappés" avec un antislash. Comme WordPress supprime ces antislashes, le code JSON devient invalide et on ne peut plus accéder à la notice.

Pour reproduire le problème rencontré par Nicolas, il suffit donc de prendre n'importe quelle notice contenant des guillemets dans le résumé et de la mettre à la corbeille. Lorsqu'il s'agit d'un lot de notices, ça plante à la première notice contenant un caractère spécial.

Ce bug WordPress n'est pas nouveau : un [ticket expliquant le problème (#27550)](https://core.trac.wordpress.org/ticket/27550) existe dans leur issue tracker depuis 17 mois mais il n'a pas encore été résolu (la résolution prend deux lignes...)

Pour essayer de faire avancer les choses, j'ai [ajouté un patch et un fichier de test au ticket](https://core.trac.wordpress.org/ticket/27550#comment:5) en espérant que la correction pourra être intégrée dans l'une des prochaines versions de WordPress...
