### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by ocormont** [docalist/docalist#380]
Message d'erreur lorsque l'on veut importer des notices, peut importe la base

Fatal error: Uncaught Error: Class 'Format d'échange Prisme (texte délimité avec ';;' et '+++')' not found in /var/www/documentation-sociale.net/web/plugins/docalist-data/class/Pages/DatabaseTools.php:70 Stack trace: #0 /var/www/documentation-sociale.net/web/plugins/docalist-data/class/Pages/DatabaseTools.php(101): Docalist\Data\Pages\DatabaseTools->getImporters(Object(Docalist\Data\Database)) #1 [internal function]: Docalist\Data\Pages\DatabaseTools->actionImport(NULL, NULL, Array) #2 /var/www/documentation-sociale.net/web/plugins/docalist-core/class/Controller.php(333): ReflectionMethod->invokeArgs(Object(Docalist\Data\Pages\DatabaseTools), Array) #3 /var/www/documentation-sociale.net/web/plugins/docalist-core/class/AdminPage.php(142): Docalist\Controller->run() #4 /var/www/documentation-sociale.net/web/wordpress/wp-includes/class-wp-hook.php(286): Docalist\AdminPage->Docalist\{closure}('') #5 /var/www/documentation-sociale.net/web/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #6 /va in /var/www/documentation-sociale.net/web/plugins/docalist-data/class/Pages/DatabaseTools.php on line 70

**Comment by daniel-menard** [comment]
Vu avec Olivier : le module d'import a été complétement ré-écrit et il faut porter le format d'import PrismeExchange vers le nouveau système.
